- 'id': 'cjnygard'
  'name': 'Carl Nygard'
  'bio': '/about-cnygard'
  'photo': '/carl-photo.jpg'
  'contacts':
    'email': ''
    'facebook': ''
    'telegram': ''
    'twitter': ''
    'github': 'cjnygard'
    'rss': ''
    'vkontakte': ''
    'linkedin': 'carl-nygard'
    'instagram': ''
    'line': ''
    'gitlab': ''
    'weibo': ''
    'codepen': ''
    'youtube': ''
    'soundcloud': ''
- 'id': 'djktno'
  'name': 'Dan Kunnath'
  'bio': '/about-dkunnath'
  'photo': '/dk-photo.jpg'
  'contacts':
    'email': ''
    'facebook': ''
    'telegram': ''
    'twitter': ''
    'github': ''
    'rss': ''
    'vkontakte': ''
    'linkedin': ''
    'instagram': ''
    'line': ''
    'gitlab': ''
    'weibo': ''
    'codepen': ''
    'youtube': ''
    'soundcloud': ''
